#!/usr/bin/env bash

function main {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"

  rbenv install -s
  gem install bundler --conservative -v "${BUNDLER_VERSION}"
  block compile bundler

  mkdir -p "$shome/bin"
  cd "$shome/bin"
  (set +f; ln -nfs ../vendor/bundle/bin/chef* ../vendor/bundle/bin/knife* ../vendor/bundle/bin/berks ../vendor/bundle/bin/ohai "$shome/bin/")
}

main "$@"
