#!/usr/bin/env bash

function main {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"

  rbenv install -s
  gem install bundler --conservative -v "${BUNDLER_VERSION}"

  bundle config build.nokogiri --use-system-libraries --with-xml2-config="$(which xml2-config)" --with-xslt-config="$(which xslt-config)"
  ln -nfs libxml2/libxml "$PKG_HOME/install/include/libxml"
  
  block compile bundler

  mkdir -p "$shome/bin"
  cd "$shome/bin"
  (set +f; ln -nfs \
    ../vendor/bundle/bin/chef* \
    ../vendor/bundle/bin/knife* \
    ../vendor/bundle/bin/berks \
    ../vendor/bundle/bin/ohai \
    ../vendor/bundle/bin/foodcritic \
    ../vendor/bundle/bin/rubocop \
    ../vendor/bundle/bin/cookstyle \
    "$shome/bin/")
}

main "$@"
